### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by MrMusic** [fruwolt/csv2joom-dev#1]
Erstmal vielen Dank für die Arbeit an diesem Script!
Nach dem Installieren gibt es beim Aufruf des Migrationsmanagers folgenden Fehler:
Parse error: syntax error, unexpected '.', expecting ',' or ';' in xxx/administrator/components/com_joomgallery/helpers/migration/migratecsv2joom.php on line 23

**Comment by fruwolt** [comment]
Hallo Alwin,

Danke fürs Interesse.. :-)

Ich hab die Installation nun schon mehrfach getestet und kenne den Fehler  
so noch nicht.  Einen offensichtlichen Syntaxfehler konnte ich bisher auch  
noch nicht finden (wonach es hier ja scheinbar aussieht) .. hmm...kannst  
Du mir sagen, welche php/Joomla/JoomGallery-Version Du einsetzt?
Vielleicht kann ich dann den Fehler reproduzieren.

Würdest Du mir außerdem bitte die   
xxx/administrator/components/com_joomgallery/helpers/migration/migratecsv2joom.php  
schicken?

Gruß
Frank





Am 11.06.2015, 14:41 Uhr, schrieb Alwin <notifications@github.com>:

>
> Erstmal vielen Dank für die Arbeit an diesem Script!
> Nach dem Installieren gibt es beim Aufruf des Migrationsmanagers  
> folgenden Fehler:
> Parse error: syntax error, unexpected '.', expecting ',' or ';' in  
> xxx/administrator/components/com_joomgallery/helpers/migration/migratecsv2joom.php  
> on >line 23
>
> —
> Reply to this email directly or view it on GitHub.



-- 
Erstellt mit Operas E-Mail-Modul: http://www.opera.com/mail/

**Comment by fruwolt** [comment]
Fehler bereits behoben - Ursache war ein Problem mit verschiedenen php-Versionen
